kind: Deployment
apiVersion: apps/v1
metadata:
    name: nginx-react
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx-react
    template:
        metadata:
            labels:
                app: nginx-react
        spec:
            containers:
                - name: nginx-react
                  image: localhost:5000/nginx-react
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
            restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
    name: nginx-react
spec:
    selector:
        app: nginx-react
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
          nodePort: 31000
